# Generated by Django 4.2.1 on 2023-08-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
